name: userapp
description: "A new Flutter project."

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_compass: any
  flutter_joystick: ^0.0.4
  flutter_map: any
  flutter_map_location_marker:
  geolocator: any
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any

flutter:
  uses-material-design: true