// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdLA7UQZQawIrmCUfa-tUrLFY9Un51j4k',
    appId: '1:677390538206:web:aa798daa9ba125e2bd394f',
    messagingSenderId: '677390538206',
    projectId: 'depanneurapp-79451',
    authDomain: 'depanneurapp-79451.firebaseapp.com',
    storageBucket: 'depanneurapp-79451.appspot.com',
    measurementId: 'G-MRQ3PDHH03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxSbIIAXd5BDL0CudI5-l2eZ8l4XtgQsg',
    appId: '1:677390538206:android:acbafa3f2cc8d295bd394f',
    messagingSenderId: '677390538206',
    projectId: 'depanneurapp-79451',
    storageBucket: 'depanneurapp-79451.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7uuSVk2OtDsPGLCsfElxDEwHbb1IGqu0',
    appId: '1:677390538206:ios:c0deee7df81071debd394f',
    messagingSenderId: '677390538206',
    projectId: 'depanneurapp-79451',
    storageBucket: 'depanneurapp-79451.appspot.com',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7uuSVk2OtDsPGLCsfElxDEwHbb1IGqu0',
    appId: '1:677390538206:ios:c0deee7df81071debd394f',
    messagingSenderId: '677390538206',
    projectId: 'depanneurapp-79451',
    storageBucket: 'depanneurapp-79451.appspot.com',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdLA7UQZQawIrmCUfa-tUrLFY9Un51j4k',
    appId: '1:677390538206:web:18a5d47384a947cfbd394f',
    messagingSenderId: '677390538206',
    projectId: 'depanneurapp-79451',
    authDomain: 'depanneurapp-79451.firebaseapp.com',
    storageBucket: 'depanneurapp-79451.appspot.com',
    measurementId: 'G-RTVJ7FT5SB',
  );
}
